"""add a foreign key column

Revision ID: 7120c0bb33de
Revises: 55a249fdee8f
Create Date: 2026-08-31 19:02:37.473113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7120c0bb33de'
down_revision = '55a249fdee8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_author', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_book_author', 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###
