"""add author relationship to books

Revision ID: 91c7c4dd82df
Revises: 42c30b799ad4
Create Date: 2026-09-01 18:24:18.887563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c7c4dd82df'
down_revision = '42c30b799ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_author_id_authors'), 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_author_id_authors'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
