"""add librarians and library_branches models

Revision ID: deda1c493a6f
Revises: 91c7c4dd82df
Create Date: 2026-09-02 18:40:47.587598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deda1c493a6f'
down_revision = '91c7c4dd82df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('librarians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_librarians')),
    sa.UniqueConstraint('email', name=op.f('uq_librarians_email'))
    )
    op.create_table('library_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_branches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_branches')
    op.drop_table('librarians')
    # ### end Alembic commands ###
