"""add an association table

Revision ID: df30df1fd0b3
Revises: 5d14f352b2a9
Create Date: 2026-09-02 19:10:54.915780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df30df1fd0b3'
down_revision = '5d14f352b2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('librarian_branches',
    sa.Column('librarian_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['library_branches.id'], name=op.f('fk_librarian_branches_branch_id_library_branches')),
    sa.ForeignKeyConstraint(['librarian_id'], ['librarians.id'], name=op.f('fk_librarian_branches_librarian_id_librarians')),
    sa.PrimaryKeyConstraint('librarian_id', 'branch_id', name=op.f('pk_librarian_branches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('librarian_branches')
    # ### end Alembic commands ###
